CREATE TABLE TBL_BOARD 
(
	IDX INT NOT NULL AUTO_INCREMENT,
	USER_IDX INT NOT NULL,
	WRITER VARCHAR(150) NOT NULL,
	TITLE VARCHAR(150) NOT NULL,
	CONTENT VARCHAR(5000) NOT NULL,
	VIEWS INT DEFAULT 0,
	IMAGE_WHETHER CHAR(1) DEFAULT FALSE,
	FILE_WHETHER CHAR(1) DEFAULT FALSE,
	VIDEO_WHETHER CHAR(1) DEFAULT FALSE,
	CREA_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(IDX)
)