CREATE TABLE TBL_BOARD_IMAGE_FILE
(
	USER_IDX INT NOT NULL,
	BOARD_IDX INT NOT NULL,
	BOARD_ORIGINAL_IMAGE_PATH VARCHAR(300) NOT NULL,
	BOARD_THUMBNAIL_IMAGE_PATH VARCHAR(300) NOT NULL,
	PRIMARY KEY(BOARD_ORIGINAL_IMAGE_PATH, BOARD_THUMBNAIL_IMAGE_PATH),
	FOREIGN KEY(USER_IDX) REFERENCES TBL_USER(IDX),
	FOREIGN KEY(BOARD_IDX) REFERENCES TBL_BOARD(IDX)
)