CREATE TABLE TBL_BOARD_FILE 
(
	USER_IDX INT NOT NULL,
	BOARD_IDX INT NOT NULL,
	BOARD_FILE_PATH VARCHAR(300) NOT NULL,
	PRIMARY KEY(BOARD_FILE_PATH),
	FOREIGN KEY(USER_IDX) REFERENCES TBL_USER(IDX),
	FOREIGN KEY(BOARD_IDX) REFERENCES TBL_BOARD(IDX)
)